version: '3'

services:
  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis://redis:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

  dashboard:
    image: cjlapao/rq-dashboard
    ports:
      - "9181:9181"
    depends_on:
      - redis
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://redis:6379
